server {
    listen 80;
    server_name _;

    root /var/www/html/api/public;
    index index.php index.html index.htm;

    # Rutas Laravel y API
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    # Ejecutar PHP
    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass 127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        # Buffers recomendados
        fastcgi_buffer_size 32k;
        fastcgi_buffers 4 32k;
    }

    # Seguridad
    location ~ /\.(?!well-known).* {
        deny all;
    }
}
